package com.example.api

import android.util.Log
import com.example.BuildConfig
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

object GeminiClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent"
    private const val TAG = "GeminiClient"

    // Fetch API Key from secure BuildConfig
    private fun getApiKey(): String {
        return BuildConfig.GEMINI_API_KEY
    }

    private val client = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    private suspend fun postRequest(prompt: String, systemInstruction: String? = null): String = withContext(Dispatchers.IO) {
        val apiKey = getApiKey()
        if (apiKey == "MY_GEMINI_API_KEY" || apiKey.isBlank()) {
            return@withContext "Error: Gemini API Key is not configured. Please add GEMINI_API_KEY in the Secrets panel."
        }

        val url = "$BASE_URL?key=$apiKey"

        try {
            // Build Gemini standard REST payload using JSON objects
            val requestBodyJson = JSONObject()
            
            val contentsArray = JSONArray()
            val contentObj = JSONObject()
            val partsArray = JSONArray()
            val partObj = JSONObject()
            partObj.put("text", prompt)
            partsArray.put(partObj)
            contentObj.put("parts", partsArray)
            contentsArray.put(contentObj)
            requestBodyJson.put("contents", contentsArray)

            if (systemInstruction != null) {
                val systemInstructionObj = JSONObject()
                val systemPartsArray = JSONArray()
                val systemPartObj = JSONObject()
                systemPartObj.put("text", systemInstruction)
                systemPartsArray.put(systemPartObj)
                systemInstructionObj.put("parts", systemPartsArray)
                requestBodyJson.put("systemInstruction", systemInstructionObj)
            }

            val requestBodyStr = requestBodyJson.toString()
            val mediaType = "application/json; charset=utf-8".toMediaType()
            val requestBody = requestBodyStr.toRequestBody(mediaType)

            val request = Request.Builder()
                .url(url)
                .post(requestBody)
                .build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    val errBody = response.body?.string() ?: ""
                    Log.e(TAG, "Request failed: Code ${response.code}, Body: $errBody")
                    return@withContext "Error calling Gemini: HTTP ${response.code}. Please ensure your API key is valid."
                }

                val responseBody = response.body?.string() ?: return@withContext "Error: Empty response from AI service."
                
                // Parse standard Gemini text candidate from response JSON
                val rootJson = JSONObject(responseBody)
                val candidates = rootJson.optJSONArray("candidates")
                if (candidates != null && candidates.length() > 0) {
                    val candidate = candidates.getJSONObject(0)
                    val content = candidate.optJSONObject("content")
                    if (content != null) {
                        val parts = content.optJSONArray("parts")
                        if (parts != null && parts.length() > 0) {
                            return@withContext parts.getJSONObject(0).optString("text")
                        }
                    }
                }
                return@withContext "No response text generated by the model."
            }
        } catch (e: Exception) {
            Log.e(TAG, "Network or JSON error", e)
            return@withContext "Request failed: ${e.localizedMessage ?: "Unknown error"}. Check your network connection."
        }
    }

    /**
     * 1. Resume bullet point generation
     */
    suspend fun generateBullets(jobTitle: String, years: String, skills: String): List<String> {
        val prompt = "Write 4 strong, high-impact resume bullet points for a $jobTitle with $years years of experience. " +
                "Incorporate skills like ($skills) if applicable. " +
                "Use active verbs, quantify results where possible, and match modern resume standards. " +
                "Return ONLY the bullet points, each on a new line (start each bullet with simple '-' and no other formatting, introductions, or chatter)."
        
        val systemMessage = "You are an elite corporate recruiter and resume consultant who writes premium Enhancv-style resume bullet points."
        val text = postRequest(prompt, systemMessage)
        
        if (text.startsWith("Error") || text.startsWith("Request failed")) {
            return listOf("Could not generate bullets: $text")
        }

        return text.split("\n")
            .map { it.trim().removePrefix("-").trim() }
            .filter { it.isNotEmpty() }
    }

    /**
     * 2. Job tailoring
     */
    suspend fun tailorResume(resumeText: String, jobDesc: String): String {
        val prompt = "Given this candidate's resume:\n\n$resumeText\n\n" +
                "And this job description for their target role:\n\n$jobDesc\n\n" +
                "Rewrite their summary statement and top 3 experience bullets to highly align with this target role. " +
                "Keep their core achievements and details authentic, but optimize the phrasing, terminology, and key action words to match. " +
                "Format the response beautifully with headings: 'Tailored Summary:' and 'Optimized Experience Bullets:'."

        val systemMessage = "You are an ATS compliance officer and professional optimizer who specializes in tailoring resumes to job descriptions."
        return postRequest(prompt, systemMessage)
    }

    /**
     * 3. ATS keyword extraction
     */
    suspend fun extractAtsKeywords(jobDesc: String): List<String> {
        val prompt = "Extract the top 12 critical ATS keywords, technologies, skills, or certifications from this job description:\n\n$jobDesc\n\n" +
                "Return ONLY a comma-separated list of these keywords. Do not explain, number, or add other text. Format exactly like: React, TypeScript, Node.js, Project Management"

        val text = postRequest(prompt, "You are a professional ATS parser.")
        if (text.startsWith("Error") || text.startsWith("Request failed")) {
            return listOf("Error fetching keywords")
        }
        return text.split(",")
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("Error:") }
    }

    /**
     * 4. Cover letter generation
     */
    suspend fun generateCoverLetter(
        name: String,
        role: String,
        company: String,
        resumeText: String,
        jobDesc: String
    ): String {
        val prompt = "Write an exceptionally polished, high-converting professional cover letter for $name " +
                "applying to the position of '$role' at '$company'.\n\n" +
                "Leverage elements of their resume:\n$resumeText\n\n" +
                "Align it precisely with the needs outlined in the job description:\n$jobDesc\n\n" +
                "Ensure it follows an elegant structure: opening hook, executive narrative of value, alignment with company mission, and a confident call to action. Keep it under 400 words."

        val systemMessage = "You are a premium career counselor who writes highly engaging, authentic cover letters that stand out."
        return postRequest(prompt, systemMessage)
    }

    /**
     * 5. Interview question generation
     */
    suspend fun generateInterviewQuestions(role: String, company: String, jobDesc: String): String {
        val prompt = "Generate the top 5 likely interview questions and professional STAR-format answer guidelines for a '$role' candidate applying to '$company' " +
                "based on this job description:\n$jobDesc\n\n" +
                "For each question, display:\n" +
                "1. Question: [The Question]\n" +
                "2. Situation/Task: [How to frame the context]\n" +
                "3. Action: [What specific skills & actions to highlight]\n" +
                "4. Result: [How to formulate a highly quantitative outcome]\n\n" +
                "Also append an elegant 2-sentence elevator pitch tailored for this role at the very end labeled 'Your Tailored Elevator Pitch:'."

        val systemMessage = "You are a senior behavioral interviewer at major global companies."
        return postRequest(prompt, systemMessage)
    }

    /**
     * 6. Fix Grammar
     */
    suspend fun fixGrammar(resumeText: String): String {
        val prompt = "Proofread, rewrite, and elevate the language of the following resume text. " +
                "Correct any typographical errors, punctuation slip-ups, or clumsy spacing. " +
                "Keep the details exactly correct but make the phrasing sound extremely executive and professional. " +
                "Return ONLY the corrected text - do not add introduction, comments, or summaries:\n\n$resumeText"
        
        return postRequest(prompt, "You are an elite professional copyeditor specializing in executive resume reviews.")
    }

    /**
     * 7. Translate Resume
     */
    suspend fun translateResume(resumeText: String, targetLanguage: String): String {
        val prompt = "Translate the following resume text into $targetLanguage. " +
                "Ensure standard translation of industry-specific jargon but keep acronyms (like AWS, SaaS) unchanged if proper. " +
                "Preserve all formatting, lines, and structural layouts. " +
                "Return ONLY the translated resume text - do not add introductions, explanations, or notes:\n\n$resumeText"

        return postRequest(prompt, "You are a multilingual professional business translator.")
    }
}
